### ISSUE TITLE
Arc Issue?

### ISSUE THREAD

**Issue by spatialfree** [Meumeu/WiVRn#1]
I'm wondering if this is just saying there is an arc issue? *Been juggling graphics cards and wonder if I need to switch again 

> [spatialfree@oldred WiVRn]$ build-server/server/wivrn-server
Service published: oldred
Server started, PID 80173
DEBUG [xrt_gfx_provider_create_system] Doing init 0x55a973787270
 INFO [create_device] Created device and GRAPHICS queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
 INFO [vk_print_device_info] Device info:
	name: Intel(R) Arc(tm) A750 Graphics (DG2)
	vendor: 0x8086
	product: 0x56a1
	apiVersion: 1.3.230
	driverVersion: 0x05803006
 INFO [vk_print_features_info] Features:
	timestamp_compute_and_graphics: true
	timestamp_period: 52.083332
	timestamp_valid_bits: 36
	timeline_semaphore: true
 INFO [vk_print_external_handles_info] Supported images:
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
		color import=true export=true
		depth import=true export=true
 INFO [vk_print_external_handles_info] Supported fences:
	VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
 INFO [vk_print_external_handles_info] Supported semaphores:
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
[in @ 0x55a973c7c880] Filters must be initialized before linking.
ERROR [comp_wivrn_create_images] Failed to create video encoder: avfilter_graph_parse_ptr failed: Invalid argument
Server exited, exit status 0
Received signal ABRT (Aborted), core dumped

**Comment by xytovl** [comment]
We don't have an ARC GPU to test, it was tested on intel iGPU and encoding worked.

However the error "Filters must be initialized before linking" is from https://github.com/FFmpeg/FFmpeg/commit/4310b66b985e5d8f4463639c007d876e4439e7a9 which is very recent.

We'll need to fix initialization apparently, could you test on an oder ffmpeg version?

**Comment by spatialfree** [comment]
oh sweet, yeah rolling back to 'ffmpeg 2:5.1.2-2' worked thx!
