### ISSUE TITLE
Hand Tracking Extension reported as supported

### ISSUE THREAD

**Issue by Schmarni-Dev** [Meumeu/WiVRn#13]
The ext_hand_tracking extension is wrongly reported as supported, which makes it impossible for an application to enable handtracking only if it is available

**Comment by xytovl** [comment]
I suppose the extension is marked as supported because it is by monado, which is used to implement OpenXR.

Calling https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#_inspect_system_capability should give supportsHandTracking = false.
