### ISSUE TITLE
hand tracking support

### ISSUE THREAD

**Issue by Astavie** [Meumeu/WiVRn#2]
love this code! I was wondering if quest hand tracking is planned?

**Comment by xytovl** [comment]
I have not looked into it at all.
Do you have a client application that requires/supports hand tracking?

**Comment by Astavie** [comment]
the [reference server](https://github.com/StardustXR/server) from [stardust xr](https://stardustxr.org/) supports hand tracking in addition to controllers!

**Comment by Meumeu** [comment]
Added in v0.12
