### ISSUE TITLE
VK_ERROR_OUT_OF_DEVICE_MEMORY in YuvConverter::YuvConverter

### ISSUE THREAD

**Issue by ElectrodeYT** [Meumeu/WiVRn#20]
It happens on this line:

```cpp
VkResult res = create_image(*vk, y.extent, y_format, y);
```

A bit of debugging shows that `extent.width` and `extent.height` (which make y.extent on line 142) are both 0 here, which strikes me as being wrong.

**Comment by xytovl** [comment]
Are you using a custom configuration?
extent should come from video width/height, and by default they will map to the detected headset screen size.

We could add a specific check here, but the issue comes from a previous step.

**Comment by ElectrodeYT** [comment]
Nope, found the bug, will send a PR in a bit

**Comment by xytovl** [comment]
That's right, video_width/height are only used for x264, as other encoders seem happy with any width/height.
When using a manual configuration, fields are initialized correctly, and default settings prefer hardware encoders when available.
