### ISSUE TITLE
Both server and client not working

### ISSUE THREAD

**Issue by rustamusmanov973** [Meumeu/WiVRn#3]
1.  SERVER  not working
I have Quest 2 headset and manjaro gnome OS.
I tried to launch wivrn-server: it stops at "Service published: machine_name" line (before the needed "Server started" output):

[user@machine_name telescope]$ sudo ufw status 
Status: inactive
[user@machine_name telescope]$ WiVRn/build-server/server/wivrn-server
Service published: machine_name

2. CLIENT not working
I connected the Quest 2 (in developer mode) headset by a cable, allowed the connection, then I ran:
[user@machine_name]$ adb install WiVRn-oculus-release.apk
It successfully installs the apk onto the Quest 2. However when I try to launch the app it opens and closes in a fraction of a second.

**Comment by xytovl** [comment]
The client is not supposed to quit immediately. Can you post client logs? You should be able to get them with `adb logcat`.

**Comment by rustamusmanov973** [comment]
OS Version: user-24721900628400000

**Comment by rustamusmanov973** [comment]
What should I do? Upgrade the firmware or downgrade it?

**Comment by xytovl** [comment]
Well I don't know, and I would have expected something like "54.0" as a version number. You can always try to see if your headset is up to date.
Also I don't have a Quest 2 to test.

Maybe building the apk with a more recent version of the SDK could fix the issue.

**Comment by rustamusmanov973** [comment]
I updated to 54.0 and now the apk works ("Wating for connection")
However when I start the server these lines are repeated:
 
DEBUG [comp_main_create_system_compositor] Doing init 0x560fe2818d40
ERROR [run] Exception in network thread: Socket shutdown
Server exited, exit status 0
