### ISSUE TITLE
OpenComposite support status

### ISSUE THREAD

**Issue by IlyaMZP** [Meumeu/WiVRn#37]
I'm currently trying to get OpenComposite working with WiVrn.
I'm able to run OpenXR apps with no issues, hello_xr starts and connects to WiVrn.
But when I try to run OpenVR games with OpenComposite installed, I get the following error in the steam log:
```
ERROR [ipc_client_socket_connect] Failed to connect to socket /run/user/1000/wivrn_comp_ipc: No such file or directory!
ERROR [ipc_client_connection_init] Failed to connect to monado service process

###
#
# Please make sure that the service process is running
#
# It is called "monado-service"
# In build trees, it is located "build-dir/src/xrt/targets/service/monado-service"
#
###
```
The `/run/user/1000/wivrn_comp_ipc` socket gets created when I launch WiVrn, so I'm not sure what the issue is.
Is this behavior expected/untested at the current stage of development or am I doing something wrong?

**Comment by xytovl** [comment]
You are running into issues with steam's "pressure vessel".

Please follow https://gitlab.com/znixian/OpenOVR/-/tree/openxr#linux-specific-info for correct setup, especially `PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/wivrn_comp_ipc` variable, be careful to use the correct name for the socket file.

You should expect the proton/OpenComposite/WiVRn stack to work well, with possible issues in button mapping and controller orientation.

**Comment by IlyaMZP** [comment]
Thanks! That worked!
