### ISSUE TITLE
ERROR [run] Exception in network thread: Socket shutdown

### ISSUE THREAD

**Issue by rustamusmanov973** [Meumeu/WiVRn#4]
The client works as expected: ("Wating for connection")
However when I start the server these lines are repeated:

[user@machine_name WiVRn]$ ./build-server/server/wivrn-server
Removing stale socket file /run/user/1000/wivrn_comp_ipc
Service published: machine_name
Server started, PID 32213
DEBUG [comp_main_create_system_compositor] Doing init 0x55c3d8a07740
ERROR [run] Exception in network thread: Socket shutdown
Server exited, exit status 0
Service published: machine_name
Server started, PID 32222
DEBUG [comp_main_create_system_compositor] Doing init 0x55c3d8a09800
ERROR [run] Exception in network thread: Socket shutdown
Server exited, exit status 0
Service published: machine_name
Server started, PID 32231
DEBUG [comp_main_create_system_compositor] Doing init 0x55c3d8a0aba0
ERROR [run] Exception in network thread: Socket shutdown
Server exited, exit status 0

**Comment by rustamusmanov973** [comment]
Logs:  
1. Started WiVRn server 
2. adb logcat
3. 1-2 seconds and I started the application in Quest 2
4. WiVRn server began to repeat lines (see above). 
5. In ~10 seconds I pressed Ctrl+C in the "adb logcat" terminal and saved as a file (attached)
[logcat_2.txt](https://github.com/Meumeu/WiVRn/files/11553013/logcat_2.txt)

**Comment by xytovl** [comment]
Do you have a firewall on PC? It should be configured to accept connections on port 9757 (TCP), 9758 (UDP) and 9759 (TCP).

**Comment by rustamusmanov973** [comment]
Ufw is disabled. I have a clean manjaro gnome install, therefore I guess there is no other firewall commands:

[user@machine_name WiVRn]$ sudo ufw status 
Status: inactive

**Comment by rustamusmanov973** [comment]
While the repeating output is produce I checked the ports with lsof:
[user@machine_name ~]$ sudo lsof -i:9757
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
wivrn-ser 21997   ec    5u  IPv6 153598      0t0  UDP msn:9758->192.168.156.190:9757 
wivrn-ser 21997   ec   11u  IPv6 163841      0t0  TCP msn:9757->192.168.156.190:32866 (CLOSE_WAIT)
[user@machine_name ~]$ sudo lsof -i:9758
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
wivrn-ser 21997   ec    5u  IPv6 153598      0t0  UDP msn:9758->192.168.156.190:9757 
[user@machine_name ~]$ 9759^C
[user@machine_name ~]$ sudo lsof -i:9759
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
wivrn-ser 21997   ec   12u  IPv6 161203      0t0  TCP *:9759 (LISTEN)
