### ISSUE TITLE
Heavy flickering and quadruple vision on Quest 3

### ISSUE THREAD

**Issue by AxelSilverdew** [Meumeu/WiVRn#41]
### The Problem
When I run VRChat (or anything else) with WiVRn, each eye sees a separate split screen. The screen also flickers a ton during this and sometimes the application (VRChat in this example) crashes too.

I have a video of this recorded from my headset here: https://www.youtube.com/watch?v=J1aNjUGbI6c

**edit:** I just wanted to emphasize that what you see in the video happens in each eye. So I'm seeing 2 different split screens.

### How I'm running things
1. Installed envision-xr-git from the AUR.
2. Installed WiVRn on my headset through envision.
3. Built the default profile in envision.
4. Hit the start button on envision.
5. Copy the launch options from envision and paste it into VRChat's launch options on steam.
6. Connected to the host from the headset using WiVRn.
7. Launch VRChat on the host in VR mode.

### My system configuration
Distro: Arch Linux
Kernel: 6.7.5-arch1-1
CPU: Ryzen 9 5900x
GPU: RX 7900 XT
Mesa: 24.0.1-arch1.1

Is there any other information I can provide to help out?
I'm not sure how to pull logs from WiVRn yet 😅

**Comment by xytovl** [comment]
To get logs from the client application, you can connect it by USB and use `adb logcat | tee logfile`, then run the application.

**Comment by xytovl** [comment]
Can you check if https://github.com/Meumeu/WiVRn/tree/fix/quest3 changes anything?
We may be using an incorrect vulkan image layout for decoder output.

I think the flickering in the video is a separate issue, can you check with "WIVRN_DUMP_VIDEO=/path/to/file" environment variable when launching the server if the issue is visible in the raw video?

**Comment by AxelSilverdew** [comment]
I tried that, but I still had the same issue.

With WIVRN_DUMP_VIDEO, this is what I got: https://youtu.be/GZDuYHlRH70
Seems like the recording is alright. But it still looks like the video in the OP through the headset.

I got a logcat, but I couldn't see any obvious error messages in it. :/

**Comment by Kierek** [comment]
https://github.com/Meumeu/WiVRn/commit/5cbaa76ad6f77517a7f4db3b625dc3c28eff92ed fixed this issue for me. No flickering and image looks fine.

**Comment by AxelSilverdew** [comment]
Can confirm, the issue was fixed in https://github.com/Meumeu/WiVRn/commit/5cbaa76ad6f77517a7f4db3b625dc3c28eff92ed
