### ISSUE TITLE
NVENC keeps being used when specifically disabled and after Encoder .cpp and .h files are removed

### ISSUE THREAD

**Issue by Resident-Fortress** [Meumeu/WiVRn#42]
Hey,

I ran the build commands to run on a Raptor i9-13900HQ IGPU. I removed the Nvenc Options and they keep being defaulted on when I run wivrn-server. I need a fix ASAP
Full Log:

 INFO [ipc_server_main]  'v21.0.0-4313-g57e93738' starting up...
DEBUG [comp_main_create_system_compositor] Doing init 0x2452460
 INFO [create_device] Created device and COMPUTE queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
 INFO [vk_print_device_info] Device info:
        name: Intel(R) Graphics (RPL-S)
        vendor: 0x8086
        product: 0xa788
        deviceType: VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        apiVersion: 1.3.267
        driverVersion: 0x05c03005
 INFO [vk_print_features_info] Features:
        timestamp_compute_and_graphics: true
        timestamp_period: 52.083332
        timestamp_valid_bits: 36
        timeline_semaphore: true
 INFO [vk_print_external_handles_info] Supported images:
        VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
                color import=true export=true
                depth import=true export=true
 INFO [vk_print_external_handles_info] Supported fences:
        VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
        VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
 INFO [vk_print_external_handles_info] Supported semaphores:
        VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
        VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
        VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
        VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
ERROR [comp_wivrn_create_images] Failed to create video encoder: Failed to create encoder nvenc
Server exited, exit status 0, received signal ABRT (Aborted), core dumped
pulseaudio module 536870913 unloaded
Service published: FaiLed-S0cketG16

**Comment by xytovl** [comment]
Please check the content of you `~/.config/wivrn.config.json`

**Comment by Resident-Fortress** [comment]
Fixed.
