### ISSUE TITLE
Code errors when building in Nix package

### ISSUE THREAD

**Issue by PassiveLemon** [Meumeu/WiVRn#44]
I am trying to package this in Nix. I've gotten to a point where an error in building is preventing me from going further and this doesn't seem like something I can troubleshoot myself. I figured I could get some support here.

The error is right at the end of the log.
[wivrn.log](https://github.com/Meumeu/WiVRn/files/14471888/wivrn.log)

If the derivation itself is useful, it's [here](https://github.com/PassiveLemon/lemonix/blob/master/pkgs/wivrn/default.nix). Not complete yet.

**Comment by xytovl** [comment]
Which version of monado are you using? I recommend using precisely the commit from the CMakeLists.txt.

You don't need to patch the CMakeLists.txt to disable downloading the libraries, in https://gitweb.gentoo.org/repo/proj/guru.git/tree/media-libs/wivrn/wivrn-0.11.ebuild we use
```
		-DFETCHCONTENT_FULLY_DISCONNECTED=ON
		-DFETCHCONTENT_BASE_DIR=${WORKDIR}
```
You then have to provide all external dependencies in the provided directory. Every tag in WiVRn has an associated "server-build-deps.tar.xz" with source dependencies.

You can also check https://github.com/NixOS/nixpkgs/pull/278126 for the official pull request.

**Comment by PassiveLemon** [comment]
Using the listed Monado version did seem to resolve it.
