### ISSUE TITLE
Enable PIE for Binaries

### ISSUE THREAD

**Issue by damaestro** [Meumeu/WiVRn#48]
We should enable CMAKE_POSITION_INDEPENDENT_CODE and set it to default ON.

Based on the fedora-review tool, there are four binaries that need addressing:

```
W: position-independent-executable-suggested /usr/bin/wivrn-server
```

Upstream Monado addressed this in https://gitlab.freedesktop.org/monado/monado/-/issues/337

**Comment by xytovl** [comment]
Shouldn't this be controlled by the packager? i.e. using `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` when invoking cmake.

**Comment by damaestro** [comment]
Setting the default is better than every downstream packaging needing to set it.
