### ISSUE TITLE
Microphone input doesn't work

### ISSUE THREAD

**Issue by AxelSilverdew** [Meumeu/WiVRn#53]
## The Problem

WiVRn doesn't capture mic input on my Quest 3.

## What I'm doing

- Start the server with Envision
- Connect to it from the headset
- Make sure that both audio input and output are set to WiVRn in my sound settings
- Try to say something into the mic, but nothing gets captured

I've tested this in both VRChat and Rumble. Neither of them can pick up my mic.

## My system configuration

Distro: Arch Linux
Kernel: 6.8.1-arch1-1
CPU: Ryzen 9 5900x
GPU: RX 7900 XT
Mesa: 24.0.1-arch1.1

**Comment by AxelSilverdew** [comment]
Fixed in https://github.com/Meumeu/WiVRn/commit/745b97c079dedd1814d3256c32b100b006aa388a

**Comment by xytovl** [comment]
merged 1aa49bb44f9b0f356c9b2de2bfa7d9d59330801c on dev
