### ISSUE TITLE
Hand tracking buggy in Half-Life Alyx

### ISSUE THREAD

**Issue by Deytron** [Meumeu/WiVRn#58]
# Specs

CPU : AMD Ryzen 5 3600x
GPU : AMD RX 6700XT
RAM : 32GB DDR4

# Hardware

Meta Quest 2, latest version

# Software
WiVRn v0.13-43-g101713e
Arch Linux, KDE 6, Wayland, Proton GE 9-2

# Issue

Hand tracking has been recently added to WiVrn 🥳 but it is half working on my Quest 2. My guess is that not all fingers are present yet as all headsets and controllers are different.
Currently thumb is not recognized, tactile detection of the index finger on the triggers are not working as well. Triggers are counted as three fingers, and grip as the other fingers + thumb.

This causes this strange issue of the hand's fingers going all over the place, as you can see here:

https://github.com/Meumeu/WiVRn/assets/20344764/6859cd15-fcfe-4283-8027-aebb97e4215c

Maybe this will be fixed when we will be able to remap everything in Monado?

**Comment by xytovl** [comment]
WiVRn forwards hand data from the headset, I am confident the issue is in OpenComposite.

In OpenXR you should have the hands correctly mapped, you can test using https://gitlab.freedesktop.org/monado/demos/openxr-simple-playground.

My testing in The Lab shows that hands are not interpreted correctly in OpenVR.

**Comment by Deytron** [comment]
Hmmmm maybe I'm missing something but OpenXR palyground and example show my controllers as cubes:

![13b4eda34359d3475a74f74c9bfc29a0](https://github.com/Meumeu/WiVRn/assets/20344764/ffbc1a32-71d1-4722-b3bd-a340fc968a2e)

WiVrn/Monado logs:

```
INFO [client_loop] Client 1 connected
 INFO [ipc_handle_instance_describe_client] Client info:
        id: 1
        application_name: 'OpenXR OpenGL Example'
        pid: 15472
        extensions:
                ext_hand_tracking_enabled: true
                ext_eye_gaze_interaction_enabled: false
                ext_hand_interaction_enabled: false
```

OpenXR playground logs:

```
[...]
Hand location 1 valid but not aim location
Hand location 0 valid but not aim location
Hand location 1 valid but not aim location
Requesting exit...
EVENT: app.oxr.session app.oxr.state changed from 5 to 4
EVENT: app.oxr.session app.oxr.state changed from 4 to 3
EVENT: app.oxr.session app.oxr.state changed from 3 to 6
EVENT: app.oxr.session app.oxr.state changed from 6 to 1
EVENT: app.oxr.session app.oxr.state changed from 1 to 8
Cleaned up!
```

If this is indeed an OpenXR issue, I will see on my side and simply close this one.

**Comment by xytovl** [comment]
The expected output of playground is:
![image](https://github.com/Meumeu/WiVRn/assets/1269670/54c3e1c4-d970-42ad-abc0-0024f0bcb351)

Controllers are displayed as one block each, hands have one block per joint.
On Quest, if a controller is visible, hand positions won't be available. When controllers go idle, hands will show up again.

**Comment by Deytron** [comment]
Alright yeah, I got the hands to show up in playground, but as you mentioned hands are not interpreted properly in The Lab and Alyx.

Since the issue seems to be unrelated to WiVrn, I'm going to close it and see if I can find anything useful on the OpenComposite side of things.
Thank you for your time!

**Comment by DocMAX** [comment]
How did you manage to run Alyx? Can you describe your setup?

**Comment by galister** [comment]
there are all issues with opencomposite and not related to wivrn
