### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by rustamusmanov973** [Meumeu/WiVRn#6]
Server not starting. 
Firewall (ufw) is inactive.

Meta quest apk works ("waiting for connection") however,
server not starting properly: shell output contains of a repeating blocks: with an error:

 [user@machine_name WiVRn]$  ./build-server/server/wivrn-server 
Removing stale socket file /run/user/1000/wivrn_comp_ipc
Service published: machine_name
Server started, PID 11886
DEBUG [comp_main_create_system_compositor] Doing init 0x5586f5588740
ERROR [run] Exception in network thread: Error on stream socket
Server exited, exit status 0
Service published: machine_name
Server started, PID 11907
DEBUG [comp_main_create_system_compositor] Doing init 0x5586f558a800
ERROR [run] Exception in network thread: Socket shutdown
Server exited, exit status 0
Service published: machine_name
....

I managed to get the "adb logcat" output. If filtered to contain "[WiVRn]" word:

06-04 16:18:15.443  4154  4191 I WiVRn   : [2023-06-04 16:18:15.443] [WiVRn] [info] Sending query for _wivrn._tcp.local., type PTR
06-04 16:18:16.312  4154  4192 I WiVRn   : [2023-06-04 16:18:16.312] [WiVRn] [info] Connection to 192.168.156.202:9757
06-04 16:18:16.513  4154  5925 I WiVRn   : [2023-06-04 16:18:16.513] [WiVRn] [info] Exception in network thread, exiting: Deserialization error
06-04 16:18:18.060  4154  4192 I WiVRn   : [2023-06-04 16:18:18.060] [WiVRn] [info] Connection to 192.168.156.202:9757
06-04 16:18:18.081  4154  5931 I WiVRn   : [2023-06-04 16:18:18.081] [WiVRn] [info] Exception in network thread, exiting: Deserialization error
06-04 16:18:20.444  4154  4191 I WiVRn   : [2023-06-04 16:18:20.444] [WiVRn] [info] Sending query for _wivrn._tcp.local., type PTR

The whole version of "adb logcat" command:
[2.txt](https://github.com/Meumeu/WiVRn/files/11645790/2.txt)

**Comment by xytovl** [comment]
We did changes to networking (especially audio), make sure to use a client and server from the same version.
Can you check if the issue persists with v0.7.1?

**Comment by rustamusmanov973** [comment]
Unfortunately I can't build the newest 0.7.1 release:
I downloaded "Source code (tar.gz)" from the releases page.
I did "cmake -B build-server . -GNinja -DWIVRN_BUILD_CLIENT=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo"
Then it failed at the command:
[user@computer WiVRn-0.7.1]$ cmake --build build-server
[0/2] Re-checking globbed directories...
[1/239] Generating version.cpp
FAILED: common/version.cpp /home/ec/git/WiVRn-0.7.1/build-server/common/version.cpp 
cd /home/ec/git/WiVRn-0.7.1/build-server/common && /usr/bin/cmake -D GIT_EXECUTABLE= -D INPUT_FILE=/home/ec/git/WiVRn-0.7.1/common/version.cpp.in -D OUTPUT_FILE=/home/ec/git/WiVRn-0.7.1/build-server/common/version.cpp -P /home/ec/git/WiVRn-0.7.1/cmake/GitVersion.cmake
fatal: not a git repository (or any of the parent directories): .git
CMake Error at /home/ec/git/WiVRn-0.7.1/cmake/GitVersion.cmake:3 (string):
  string sub-command STRIP requires two arguments.


[14/239] Building C object _deps/monado-build/src/xrt/auxiliary/ogl/CMakeFiles/aux_ogl.dir/ogl_api.c.o
ninja: build stopped: subcommand failed.


More details in the attach:
[a.txt](https://github.com/Meumeu/WiVRn/files/12194690/a.txt)

**Comment by xytovl** [comment]
The build only works from a git checkout currently, or by manually setting `-DGIT_DESC=<any version name>` cmake variable.

**Comment by rustamusmanov973** [comment]
Thanks, now the building is successful.
However when I open the WiVRn apk for Quest 2 from the latest release this happens on the computer: I get repeating fragments:

(base) [user@computer_name WiVRn-0.7.1]$ build-server/server/wivrn-server
Removing stale socket file /run/user/1000/wivrn_comp_ipc
Service published: computer_name
Server started, PID 64455
DEBUG [comp_main_create_system_compositor] Doing init 0x562683ec3060
 INFO [create_device] Created device and GRAPHICS queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
 INFO [vk_print_device_info] Device info:
	name: AMD Radeon Graphics (RADV RENOIR)
	vendor: 0x1002
	product: 0x164c
	apiVersion: 1.3.238
	driverVersion: 0x05c00004
 INFO [vk_print_features_info] Features:
	timestamp_compute_and_graphics: true
	timestamp_period: 10.000000
	timestamp_valid_bits: 64
	timeline_semaphore: true
 INFO [vk_print_external_handles_info] Supported images:
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
		color import=true export=true
		depth import=true export=true
 INFO [vk_print_external_handles_info] Supported fences:
	VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
 INFO [vk_print_external_handles_info] Supported semaphores:
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
[hevc_vaapi @ 0x562684242b00] No usable encoding profile found.
ERROR [comp_wivrn_create_images] Failed to create video encoder: Cannot open video encoder codec: Function not implemented
Server exited, exit status 0, received signal ABRT (Aborted), core dumped
pulseaudio module 38 unloaded
Service published: computer_name
Server started, PID 64498
DEBUG [comp_main_create_system_compositor] Doing init 0x562683ec5100
 INFO [create_device] Created device and GRAPHICS queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
 INFO [vk_print_device_info] Device info:
	name: AMD Radeon Graphics (RADV RENOIR)
	vendor: 0x1002
	product: 0x164c
	apiVersion: 1.3.238
	driverVersion: 0x05c00004
 INFO [vk_print_features_info] Features:
	timestamp_compute_and_graphics: true
	timestamp_period: 10.000000
	timestamp_valid_bits: 64
	timeline_semaphore: true
 INFO [vk_print_external_handles_info] Supported images:
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
		color import=true export=true
		depth import=true export=true
 INFO [vk_print_external_handles_info] Supported fences:
	VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
 INFO [vk_print_external_handles_info] Supported semaphores:
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
[hevc_vaapi @ 0x5626842455c0] No usable encoding profile found.
ERROR [comp_wivrn_create_images] Failed to create video encoder: Cannot open video encoder codec: Function not implemented
Server exited, exit status 0, received signal ABRT (Aborted), core dumped
pulseaudio module 39 unloaded
Service published: computer_name
Server started, PID 64538
DEBUG [comp_main_create_system_compositor] Doing init 0x562683ec64d0
 INFO [create_device] Created device and GRAPHICS queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
 INFO [vk_print_device_info] Device info:
	name: AMD Radeon Graphics (RADV RENOIR)
	vendor: 0x1002
	product: 0x164c
	apiVersion: 1.3.238
	driverVersion: 0x05c00004
 INFO [vk_print_features_info] Features:
	timestamp_compute_and_graphics: true
	timestamp_period: 10.000000
	timestamp_valid_bits: 64
	timeline_semaphore: true
 INFO [vk_print_external_handles_info] Supported images:
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
		color import=true export=true
		depth import=true export=true
 INFO [vk_print_external_handles_info] Supported fences:
	VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
 INFO [vk_print_external_handles_info] Supported semaphores:
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
[hevc_vaapi @ 0x562684298e80] No usable encoding profile found.
ERROR [comp_wivrn_create_images] Failed to create video encoder: Cannot open video encoder codec: Function not implemented
Server exited, exit status 0, received signal ABRT (Aborted), core dumped
pulseaudio module 40 unloaded
Service published: comuter_name

**Comment by xytovl** [comment]
I suppose you are using a distribution that doesn't support hevc hardware encoding. You can try `vainfo` utility to check what is supported.

Smart auto-configuration is a planned feature, and for now we have a dumb mapping nvidia -> nvenc, anything else -> hevc vaapi.

If you are unable to get vaapi working on your device, you can use manual encoder configuration as described in https://github.com/Meumeu/WiVRn/releases/tag/v0.3
For instance:
```json
{
    "encoders": [
        {
			"encoder": "x264",
			"bitrate": 50000000,
			"codec": "h264",
			"width": 1,
			"height": 1,
			"offset_x": 0,
			"offset_y": 0,
                        "group": 0
        }
    ]
}
```

**Comment by rustamusmanov973** [comment]
Everything is working. Thank you very much!
