### ISSUE TITLE
Issue - Pico 4 Client Stuck on "Waiting for Connection"

### ISSUE THREAD

**Issue by SiyaoHuang** [Meumeu/WiVRn#60]
I am encountering an issue with the WiVRn v0.14.1 where a Pico 4 client is displaying "waiting for connection" and the server does not show any further activity. The server logs provided are as follows:

```
build-server/server/wivrn-server
WiVRn v0.14.1 starting
Removing stale socket file /run/user/1000/wivrn_comp_ipc
Service published: unity
After this, the logs do not provide any additional information regarding the connection attempt.
```

Steps to Reproduce:

Launch the WiVRn server.
Attempt to connect using a Pico 4 client.
Observe that the Pico 4 client remains on a "waiting for connection" message.

I have tried restarting both the server and the Pico 4 client, but the issue persists.
I am seeking assistance in troubleshooting and resolving this connection issue. Any guidance would be greatly appreciated.

**Comment by xytovl** [comment]
Do you have a firewall? If so make sure ports 9757 TCP and UDP are open: https://github.com/Meumeu/WiVRn?tab=readme-ov-file#prerequisites

**Comment by xytovl** [comment]
If you could provide client logs (using `adb logcat`), this will help analyze the issue.

**Comment by SiyaoHuang** [comment]
> Do you have a firewall? If so make sure ports 9757 TCP and UDP are open: https://github.com/Meumeu/WiVRn?tab=readme-ov-file#prerequisites

I checked my ubuntu setting by terminal. The firewall seems inactive
```
$ sudo ufw status
Status: inactive
```

I am trying to build the client for more debug information.

**Comment by SiyaoHuang** [comment]
[logcat.txt](https://github.com/Meumeu/WiVRn/files/15159045/logcat.txt)
This is the output of logcat. I would add more log for debugging.

**Comment by xytovl** [comment]
Logs have
> [2024-04-30 14:12:12.798] [WiVRn] [warning] Cannot connect to unity-7 (10.86.97.144): Connection timed out

I will try to have the correct error displayed on the headset.

For your issue, it looks like a networking problem, either incorrect address reported by avahi or routing problem.

**Comment by SiyaoHuang** [comment]
Update: My bad server and client are using different WIFI connections. So server and client cannot reach each other.

There is new error on server. I would dig into it or try h264_vaapi instead. Thank you.
```
[hevc_vaapi @ 0x58e1ae7ffa80] Driver does not support any RC mode compatible with selected options (supported modes: CQP).
```

**Comment by SiyaoHuang** [comment]
After disable all the hard encoding and switch to software encoding. Everything works.
```
cmake -B build-server . -GNinja -DWIVRN_BUILD_CLIENT=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWIVRN_USE_X264=ON -DWIVRN_USE_VAAPI=OFF -DWIVRN_USE_NVENC=OFF
```
I would do more research to make the vaapi working.

**Comment by xytovl** [comment]
Encoders can be configured at run-time, see https://github.com/Meumeu/WiVRn/blob/master/docs/configuration.md

The log suggests that your GPU does not support rate control for h265. You may try setting the codec to h264, still on vaapi.
I do not know how to detect the features for vaapi, therefore default settings may be invalid.

**Comment by SiyaoHuang** [comment]
> Encoders can be configured at run-time, see https://github.com/Meumeu/WiVRn/blob/master/docs/configuration.md
> 
> The log suggests that your GPU does not support rate control for h265. You may try setting the codec to h264, still on vaapi. I do not know how to detect the features for vaapi, therefore default settings may be invalid.

Yesterday, I tried vaapi both h264 and h264, failed. And try nvcc, the server runs and get the input, but the headset did not recieve the video stream. So, I turn of all the hard encoding. To check if other thing works.

My friend got vaapi works on his computer. I guess there is something wrong with my driver. I am using ubuntu 22.04.

**Comment by xytovl** [comment]
What is you GPU and what is the output of `vainfo`?

**Comment by SiyaoHuang** [comment]
after install nvidia driver by ```sudo ubuntu-drivers install nvidia:535``` the `nvenc` works. There's some screen tearing while streaming.

I am working on vaapi. The curren error is.
```
[AVHWDeviceContext @ 0x5abcee2b8240] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[AVHWDeviceContext @ 0x5abcee2b8240] Failed to initialise VAAPI connection: -1 (unknown libva error).
ERROR [comp_wivrn_create_images] Failed to create video encoder: FFMPEG vaapi hardware context creation failed: Input/output error
```

vainfo is
```
unity@unity:~$ vainfo
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
unity@unity:~$ vainfo --display drm 
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```
