### ISSUE TITLE
Client crashing at startup

### ISSUE THREAD

**Issue by Globibluk** [Meumeu/WiVRn#65]
Hi,

First of all, thank for your work on this app!
Yesterday the app worked fine, but today it seems to crash at startup with the following logs.

> 05-15 10:33:28.692   812   812 D SurfaceFlinger: Found VR App layer dName:SurfaceView - org.meumeu.wivrn/android.app.NativeActivity#0
> 05-15 10:33:32.898  9837  9876 I WiVRn   : [2024-05-15 10:33:32.898] [WiVRn] [info] Sending query for _wivrn._tcp.local., type PTR
> 05-15 10:33:33.271   812   812 D SurfaceFlinger: Found VR App layer dName:SurfaceView - org.meumeu.wivrn/android.app.NativeActivity#0
> 05-15 10:33:35.803  1224  1367 W InputDispatcher: channel 'b3d02c5 org.meumeu.wivrn/android.app.NativeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 05-15 10:33:35.803  1224  1367 E InputDispatcher: channel 'b3d02c5 org.meumeu.wivrn/android.app.NativeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 05-15 10:33:35.817  1761  2533 D VROverlayServiceManager: binderDied() mName = org.meumeu.wivrn mCb = com.htc.vr.sdk.overlay.IVROverlayActivityCallback$Stub$Proxy@f540fab
> 05-15 10:33:35.818  1728  3241 I VROEM_VRCustomizedOEMService_api1: binderDied: client= (pid=9837, uid=10068, name=org.meumeu.wivrn)@8f2a4a3
> 05-15 10:33:35.818  1728  3241 I VRSharingService: unregisterClient : remove OEMClientRecord (pid=9837, uid=10068, name=org.meumeu.wivrn)@150119587
> 05-15 10:33:35.818  1728  3241 D VRSharingService: call unregisterClient : (pid=9837, uid=10068, name=org.meumeu.wivrn)@150119587
> 05-15 10:33:35.818  1224  1803 I ActivityManager: Process org.meumeu.wivrn (pid 9837) has died: fore TOP 
> 05-15 10:33:35.818  1728  3241 I VRSharingService: unregisterClient : remove streamingOEMClient (pid=9837, uid=10068, name=org.meumeu.wivrn)@150119587
> 05-15 10:33:35.818  1728  3241 I VRSharingService: binderDied: client= (pid=9837, uid=10068, name=org.meumeu.wivrn)@150119587
> 05-15 10:33:35.818  1224  2919 I WindowManager: WIN DEATH: Window{b3d02c5 u0 org.meumeu.wivrn/android.app.NativeActivity}
> 05-15 10:33:35.818  1224  2919 W InputDispatcher: Attempted to unregister already unregistered input channel 'b3d02c5 org.meumeu.wivrn/android.app.NativeActivity (server)'
> 05-15 10:33:35.821   812   812 D SurfaceFlinger: Found VR App layer dName:SurfaceView - org.meumeu.wivrn/android.app.NativeActivity#0
> 05-15 10:33:35.847  1951  2865 D LifeCycleManager: registerProcessObserver: onProcessDied PID=9837 UID=10068(org.meumeu.wivrn)
> 05-15 10:33:35.860  1951  9562 D LifeCycleManager: onUidIdle: UID:10068[org.meumeu.wivrn] | Disabled:false
> 05-15 10:33:35.881  1951  2865 D LifeCycleManager: setUidPaused: UID=10068 PID=-1 | PKG Name=org.meumeu.wivrn
> 05-15 10:33:35.881  1951  2865 D LifeCycleManager: isXrApp: start:org.meumeu.wivrn
> 05-15 10:33:35.883  1728  3241 D VRDialogOverlayService: setForegroundAppName()org.meumeu.wivrn, new : com.htc.vrs.launcher
> 05-15 10:33:35.888  1728  3241 D VROEM EUSEnvironmentChecker: updateAliveApps() killedApp: org.meumeu.wivrn, getAllApps : com.htc.vrs.launcher
> 05-15 10:33:35.888  1728  3241 D VROEM EUSEnvironmentChecker: updateBgAppListVive : remove org.meumeu.wivrn
> 05-15 10:33:35.888  1728  3241 D UtilsFunc: cleanBackgroundAPInDB, packageName: org.meumeu.wivrn
> 05-15 10:33:35.893  1951  9562 D LifeCycleManager: registerProcessObserver: onUidIdle UID=10068(org.meumeu.wivrn) Disable=false
> 05-15 10:33:35.903  1728  3241 D OEM_VRConfigService: getKeyValue: Value of Key[current_bg_ap_list] retrieved : [org.meumeu.wivrn] .
> 05-15 10:33:35.903  1728  3241 D UtilsFunc: cleanBackgroundAPInDB, currentAppList: org.meumeu.wivrn
> 05-15 10:33:35.942  1728  1760 D VROEM EUSEnvironmentChecker: updateBgAppListVive : add org.meumeu.wivrn
> 05-15 10:33:35.944  1951  2865 D LifeCycleManager: isXrApp: start:org.meumeu.wivrn
> 05-15 10:33:35.944  1951  9562 D LifeCycleManager: onUidGone: UID:10068[org.meumeu.wivrn] | Disabled:false
> 05-15 10:33:35.944  1951  9562 D LifeCycleManager: registerProcessObserver: onUidGone UID=10068(org.meumeu.wivrn)
> 05-15 10:33:36.148  1728  1728 D VROEM EUSEnvironmentChecker: updateBgAppListVive : Last launched ap into DB  ++= [org.meumeu.wivrn]
> 05-15 10:33:36.148  1728  1728 D OEM_VRConfigService: setKeyValue: Set  Key[current_bg_ap_list_vive] :: [org.meumeu.wivrn] cache into cache.
> 05-15 10:33:36.148  1728  1728 D OEMData : SetString :: current_bg_ap_list_vive => org.meumeu.wivrn || Uri /eus_config/system
> 05-15 10:33:36.169  2193  9818 D vportS  : [AppIconUtil] getIconPath: pkg=org.meumeu.wivrn,1t=1715701421339,2t=1715764784462
> 05-15 10:33:36.214  2193  9937 D vportS  : [AppIconUtil] getIconPath: pkg=org.meumeu.wivrn,1t=1715701421339,2t=1715764784462
> 05-15 10:33:36.227  2193  9936 D vportS  : [AppIconUtil] getIconPath: pkg=org.meumeu.wivrn,1t=1715701421339,2t=1715764784462
> 05-15 10:33:36.319  2193  2456 I Unity   : [Library] unpin app id=org.meumeu.wivrn

I use a HTC XR Pro, the latest release and build.
Please ask if you need more information.

**Comment by xytovl** [comment]
Is that all there is in logs? it doesn't even print an error.

If you can reproduce under debugger does it provide more information?
Also I see that HTC XR elite had an update today, this could be the cause.

**Comment by xytovl** [comment]
I tested on my headset: right after the update it would crash on start. After reinstalling WiVRn (to be able to debug), it no longer crashes. Reinstalling the standard version no longer crashes either.
If it behaves the same for you I will assume this is a bug in HTC update and we can close the issue.

**Comment by Globibluk** [comment]
It seems to work now, thanks a lot!
