### ISSUE TITLE
Reconnection support

### ISSUE THREAD

**Issue by xytovl** [Meumeu/WiVRn#68]
### Problem description
When conection is terminated, server terminates the OpenXR session, running applications will either crash or quit.

### Proposed solution
When connection is terminated, server switches session state to idle (may need an update in monado) and wait for a user-configurable time. If no OpenXR application are running, the server can terminate immediately.

If a new connection is established within the given time, operations resume on the new connection. If no connection is received, server terminates the session.

## Usability details
When connecting and a session is already running, the client should offer a prompt through GUI to resume the session or start a new one.

We should make sure that it is possible to terminate stale sessions from the server.

## Technical details
The master and child processes should share an unix socket so that master process can communicate the new file descriptors, and child process can signal loss of connection.

The exception used to notify of the disconnected socket should provide a mechanism to wait for the new session.

When resuming a session, handshake should be replayed, video and audio stream description reissued and video stream reset (roll back to frame 0, request an IDR). Audio buffers should be flushed.

**Comment by galister** [comment]
as of current [d90863c](https://github.com/Meumeu/WiVRn/commit/d90863c9b408af913b9f6e82bc5fc47717e7dc75); about once every 10 or so reconnect attempts, the client will get "video stream interrupted", with seemingly no way to reconnect without restarting wivrn-server.

**Comment by xytovl** [comment]
> as of current [d90863c](https://github.com/Meumeu/WiVRn/commit/d90863c9b408af913b9f6e82bc5fc47717e7dc75); about once every 10 or so reconnect attempts, the client will get "video stream interrupted", with seemingly no way to reconnect without restarting wivrn-server.

If this is nvidia-specific, it might be an error in the way IDR as issued:
https://github.com/Meumeu/WiVRn/tree/fix-reconnect fixes an incorrect usage of flags.

**Comment by galister** [comment]
Don't think so, I'm actually using AMD

**Comment by xytovl** [comment]
Do you have specific steps to reproduce? Some application that triggers it more often?

A backtrace of all threads when it is stalled could be useful. There has been issues at some point with pacer getting absurd times (negative time values interpreted as unsigend), so it could be blocked in the app pacer code.

**Comment by galister** [comment]
It's rare enough that I'm usually not ready to pull logs or dump the core when it hits. Usually happens after I leave the headset and come back 10+ minutes later. Even then, it's quite rare. I'll try to get a bt next time.

**Comment by xytovl** [comment]
Please create a new issue when you are able to reproduce the issue. I am closing this one, as the feature is released.
