### ISSUE TITLE
"latest" release download not present on the repo

### ISSUE THREAD

**Issue by SpookySkeletons** [Meumeu/WiVRn#7]
Hello, we're unable to pull the latest APK version of WiVRn from the release page of the git.

Is this something that was not enabled or perhaps a tag must be created to handle?

**Comment by SpookySkeletons** [comment]
Noticed all your release objects are pre-release.

Might you enable a release state on the v0.4 tag and up to enable grabbing of latest one if this is what's preventing it from working?

**Comment by xytovl** [comment]
I didn't realize the "pre-release" status would hide it from downloads.
I've removed the tag for 0.4.

**Comment by SpookySkeletons** [comment]
Thankyou!
We're shipping these bins with the Rex2 orchestrator for auto install and configuration of XR on linux.

https://gitlab.com/gabmus/rex2
