### ISSUE TITLE
Flag to specify the configuration file to use

### ISSUE THREAD

**Issue by PassiveLemon** [Meumeu/WiVRn#75]
I think it would be useful to have a flag to specify a configuration file to use. Would be much easier to swap between configurations without having to modify files.
Ex: `wivrn-server -f ~/.config/wivrn/specialconfig.json`

**Comment by xytovl** [comment]
Added in https://github.com/Meumeu/WiVRn/commit/8a96729983d69a2158f8b58bf8f02e542f5a2af6 (dev branch)
