### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by KSI65** [Meumeu/WiVRn#81]
Hi,
I tried to build on my linux mint system & invoked the 2 build commands.
First one, "cmake -B build-server . -GNinja -DWIVRN_BUILD_CLIENT=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo" goes through & creates the build-server subdirectory
Second one "cmake -build --build-server" returns with  "ninja: no work to do"

I'm sure I'm missing something basic. But I can't figure it out. 
Thanks,

**Comment by xytovl** [comment]
If the command is exactly as you typed, the `-` are incorrect, it should be `cmake --build build-server`

That command is equivalent to `ninja -C build-server`, also equivalent to `ninja` from the `build-server` directory.

If this does not fix the issue please delete the directory, run the commands again and post the complete output.

**Comment by KSI65** [comment]
OK, I made a typo above. Here is the output:

KSI@ksi-Z690-UD-DDR4:~/Downloads/boostpfr-src$ cmake -B build-server . -GNinja -DWIVRN_BUILD_CLIENT=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WIVRN_BUILD_CLIENT


-- Build files have been written to: /home/KSI/Downloads/boostpfr-src/build-server
KSI@ksi-Z690-UD-DDR4:~/Downloads/boostpfr-src$ cmake --build build-server
ninja: no work to do.
KSI@ksi-Z690-UD-DDR4:~/Downloads/boostpfr-src$ cmake --build build-server
ninja: no work to do.
KSI@ksi-Z690-UD-DDR4:~/Downloads/boostpfr-src$ ninja -C build-server
ninja: Entering directory `build-server'
ninja: no work to do.

Thanks

**Comment by xytovl** [comment]
You should run the command from the checkout directory, which by default will be `WiVRn`. It seems you downloaded the dependencies instead. Those are only needed for offline build, where you do not want to download files during the build process, essentially for distribution packaging.

**Comment by KSI65** [comment]
It was something very basic. Apologies for the mix-up. Closing the issue as it's not an issue.
