### ISSUE TITLE
Controller Tracking is unusable

### ISSUE THREAD

**Issue by EnderSpy29** [Meumeu/WiVRn#87]
Pico 4
Arch Linux, built WiVRn server from git. Full AMD system

Tracking is terrible, and its making games like beat saber unusable. its only when using WiVRn. anything else in the headset itself is perfect.

Symptoms:
Controllers are really wobbly and will randomly start having a seizure when ever you move them kinda quickly.. but i haven't found a consistent trigger. i believe the Network/latency graph spikes a bit whenever this issue occurs.

**Comment by xytovl** [comment]
What is the reported "motions to photon" latency? It is displayed on performance metrics on latest master builds.

**Comment by EnderSpy29** [comment]
i uhh, don't have that. 
![image](https://github.com/Meumeu/WiVRn/assets/93895106/a951f83d-e04b-44d9-9a91-9038d5fc6c82)

**Comment by EnderSpy29** [comment]
maybe my APK needs updating?

**Comment by xytovl** [comment]
It was added in https://github.com/Meumeu/WiVRn/commit/ae8a6fa6b3275a45eda0ee48ec79462a040f5485, not present in v0.16 release.
Please use a build from https://github.com/Meumeu/WiVRn/actions/workflows/Build.yml?query=branch%3Amaster

It is recommended to use a matching client and server version, especially because some tweaks were made regarding controller tracking.

**Comment by EnderSpy29** [comment]
right, i'll try that. i kinda gave up on compiling the Android APK so i was using v0.16....

**Comment by EnderSpy29** [comment]
Ok sweet that fixed it. controllers work perfectly now. The motions to photon Latency is around 60-80ms same as the general network latency.
Any tips on optimizing latency?

**Comment by xytovl** [comment]
60ms is not bad, while 80ms starts to be an issue.

In both cases this should not be high enough to cause uncontrolled wobble.

If you want to reduce latency, you can reduce scale on server configuration (0.5 should be fine).
You can also use multiple encoders to save about 2ms, here is the sample configuration on AMD:
```json
{
    "encoders": [
		{
			"encoder": "vaapi",
			"width": 0.5,
			"height": 0.25,
			"offset_x": 0,
			"offset_y": 0,
			"group": 0,
			"codec": "h265"
		},
		{
			"encoder": "vaapi",
			"width": 0.5,
			"height": 0.75,
			"offset_x": 0,
			"offset_y": 0.25,
			"group": 0,
			"codec": "h265"
		},
		{
			"encoder": "x264",
			"width": 0.5,
			"height": 1,
			"offset_x": 0.5,
			"offset_y": 0,
			"group": 1,
			"codec": "h264"
		}
	]
}
```
