### ISSUE TITLE
Implement XR_SESSION_STATE_READY on server side

### ISSUE THREAD

**Issue by DanielKinsman** [Meumeu/WiVRn#95]
From what I can see this event isn't passed to the application running on the server side of the fence? When I use godot to try and hook into the [XRInterface.session_begun](https://docs.godotengine.org/en/stable/classes/class_openxrinterface.html#signals) signal it doesn't work on wivrn, and [under the hood](https://github.com/godotengine/godot/blob/master/modules/openxr/openxr_api.cpp#L1948) it looks like that uses `XR_SESSION_STATE_READY` to do so. Typically in godot you'd use that signal to sync up the refresh rate and physics simulation rate as shown [here](https://github.com/GodotVR/godot-xr-tools/blob/master/addons/godot-xr-tools/xr/start_xr.gd#L283).

**Comment by xytovl** [comment]
The `XR_SESSION_STATE_READY` is already emitted by monado itself: https://gitlab.freedesktop.org/monado/monado/-/blob/e4636ca15303e2b932294d3c8a07b7cd53d482fb/src/xrt/state_trackers/oxr/oxr_session.c?page=2#L1153

We do not forward visible/focused/stopping events and they remain linked to connection state instead of state on headset.

**Comment by DanielKinsman** [comment]
I don't know how wivrn and monado are connected, I have wivrn installed from aur but do not have monado separately installed. All I really know is that the godot signal `XRInterface.session_begun` is not working in wivrn, but it works in alvr + steamvr on linux, as well as on windows using VDXR and other runtimes.

You know way more than me about all this so please go ahead and close this issue if you think it is a problem with godot, monado, or my setup and not wivrn's problem or responsibility.

**Comment by xytovl** [comment]
WiVRn embeds its own copy of monado, which provides the OpenXR interface.

Can you verify with hello_xr that session correctly starts?
It should log session state changes events: https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/650f7514c16382828e363146b78330cc365cd83e/src/tests/hello_xr/openxr_program.cpp#L730

Sequence should be: start wivrn-server, start headset application, select "connect", when "waiting for video stream" appears, start the PC OpenXR application.

**Comment by DanielKinsman** [comment]
It appears the problem was with my own code. After hello_xr indicated success, I did some more digging and found the error.

My sincere apologies for wasting your time.
